In [1]:
import pandas as pd

# Cargar el archivo CSV
csv_path = "conjunto_de_datos/denue_inegi_62_.csv"
df = pd.read_csv(csv_path, encoding='latin-1')  # Try 'latin-1' encoding

print(df.head())

df.head()

/home/luise/miniconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/tmp/ipykernel_10618/1917405623.py:5: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path, encoding='latin-1')  # Try 'latin-1' encoding

        id                          clee              nom_estab  \
0      536  01003624191000011001000000S3    AA GRUPO CHICAGO 85
1  8625042  01001624191002591000000000U6    AA GRUPO LA SOLEDAD
2    16651  01001624191000421001000000U8     AA GRUPO PRIMAVERA
3  8463387  01001624211000123000000000S6  ABASTOS Y OPERACIONES
4  8984759  01001623311000112000000000U8      ABUELITOS FELICES

                                      raz_social  codigo_act  \
0                                            NaN      624191
1  CENTRAL MEXICANA DE SERVICIOS GENERALES AA AC      624191
2                          AA GRUPO PRIMAVERA AC      624191
3                 ABASTOS Y OPERACIONES SA DE CV      624211
4                     ABUELITOS FELICES S DE SS       623311

                                          nombre_act           per_ocu  \
0  Agrupaciones de autoayuda para alcohólicos y p...  11 a 30 personas
1  Agrupaciones de autoayuda para alcohólicos y p...    0 a 5 personas
2  Agrupaciones de autoayuda para alcohólicos y p...   6 a 10 personas
3  Servicios de alimentación comunitarios prestad...  11 a 30 personas
4  Asilos y otras residencias del sector privado ...   6 a 10 personas

  tipo_vial            nom_vial tipo_v_e_1  ...  \
0     CALLE             ABASOLO      CALLE  ...
1     CALLE          ATOTONILCO      CALLE  ...
2     CALLE               ALAMO      CALLE  ...
3     CALLE           INDUSTRIA    AVENIDA  ...
4   PRIVADA  VALLE DE GUADALUPE      CALLE  ...

                                           localidad  ageb manzana  \
0  Calvillo                                      ...  0187      24
1                                     Aguascalientes  2846      15
2                                     Aguascalientes  0464       8
3                                     Aguascalientes  198A       4
4                                     Aguascalientes  2278      17

       telefono                   correoelec  www tipoUniEco    latitud  \
0  4951077786.0                          NaN  NaN       Fijo  21.845172
1           NaN                          NaN  NaN       Fijo  21.877198
2           NaN                          NaN  NaN       Fijo  21.893899
3           NaN  ABASTOSYOPERACION@GMAIL.COM  NaN       Fijo  21.905559
4           NaN                          NaN  NaN       Fijo  21.910645

     longitud  fecha_alta
0 -102.722171     2010-07
1 -102.333976     2019-11
2 -102.295940     2010-07
3 -102.290243     2019-11
4 -102.304349     2019-11

[5 rows x 42 columns]

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,...,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta
0,536,01003624191000011001000000S3,AA GRUPO CHICAGO 85,NaN,624191,Agrupaciones de autoayuda para alcohólicos y p...,11 a 30 personas,CALLE,ABASOLO,CALLE,...,Calvillo ...,0187,24,4951077786.0,NaN,NaN,Fijo,21.845172,-102.722171,2010-07
1,8625042,01001624191002591000000000U6,AA GRUPO LA SOLEDAD,CENTRAL MEXICANA DE SERVICIOS GENERALES AA AC,624191,Agrupaciones de autoayuda para alcohólicos y p...,0 a 5 personas,CALLE,ATOTONILCO,CALLE,...,Aguascalientes,2846,15,NaN,NaN,NaN,Fijo,21.877198,-102.333976,2019-11
2,16651,01001624191000421001000000U8,AA GRUPO PRIMAVERA,AA GRUPO PRIMAVERA AC,624191,Agrupaciones de autoayuda para alcohólicos y p...,6 a 10 personas,CALLE,ALAMO,CALLE,...,Aguascalientes,0464,8,NaN,NaN,NaN,Fijo,21.893899,-102.295940,2010-07
3,8463387,01001624211000123000000000S6,ABASTOS Y OPERACIONES,ABASTOS Y OPERACIONES SA DE CV,624211,Servicios de alimentación comunitarios prestad...,11 a 30 personas,CALLE,INDUSTRIA,AVENIDA,...,Aguascalientes,198A,4,NaN,ABASTOSYOPERACION@GMAIL.COM,NaN,Fijo,21.905559,-102.290243,2019-11
4,8984759,01001623311000112000000000U8,ABUELITOS FELICES,ABUELITOS FELICES S DE SS,623311,Asilos y otras residencias del sector privado ...,6 a 10 personas,PRIVADA,VALLE DE GUADALUPE,CALLE,...,Aguascalientes,2278,17,NaN,NaN,NaN,Fijo,21.910645,-102.304349,2019-11

In [2]:
# Get the list of column names from the dataframe
column_names = df.columns.tolist()
print(column_names)

['id', 'clee', 'nom_estab', 'raz_social', 'codigo_act', 'nombre_act', 'per_ocu', 'tipo_vial', 'nom_vial', 'tipo_v_e_1', 'nom_v_e_1', 'tipo_v_e_2', 'nom_v_e_2', 'tipo_v_e_3', 'nom_v_e_3', 'numero_ext', 'letra_ext', 'edificio', 'edificio_e', 'numero_int', 'letra_int', 'tipo_asent', 'nomb_asent', 'tipoCenCom', 'nom_CenCom', 'num_local', 'cod_postal', 'cve_ent', 'entidad', 'cve_mun', 'municipio', 'cve_loc', 'localidad', 'ageb', 'manzana', 'telefono', 'correoelec', 'www', 'tipoUniEco', 'latitud', 'longitud', 'fecha_alta']

In [3]:
# Select only the specified columns from the dataframe
selected_columns = ['clee', 'nom_estab', 'codigo_act', 'per_ocu', 'cve_ent', 'cve_mun', 'cve_loc', 'ageb', 'municipio', 'entidad', 'localidad']
df_selected = df[selected_columns]

print(df_selected.head())

                           clee              nom_estab  codigo_act  \
0  01003624191000011001000000S3    AA GRUPO CHICAGO 85      624191
1  01001624191002591000000000U6    AA GRUPO LA SOLEDAD      624191
2  01001624191000421001000000U8     AA GRUPO PRIMAVERA      624191
3  01001624211000123000000000S6  ABASTOS Y OPERACIONES      624211
4  01001623311000112000000000U8      ABUELITOS FELICES      623311

            per_ocu  cve_ent  cve_mun  cve_loc  ageb       municipio  \
0  11 a 30 personas        1        3        1  0187        Calvillo
1    0 a 5 personas        1        1        1  2846  Aguascalientes
2   6 a 10 personas        1        1        1  0464  Aguascalientes
3  11 a 30 personas        1        1        1  198A  Aguascalientes
4   6 a 10 personas        1        1        1  2278  Aguascalientes

          entidad                                          localidad
0  Aguascalientes  Calvillo                                      ...
1  Aguascalientes                                     Aguascalientes
2  Aguascalientes                                     Aguascalientes
3  Aguascalientes                                     Aguascalientes
4  Aguascalientes                                     Aguascalientes

In [4]:
# Load the second CSV file
csv_path2 = "conjunto_de_datos_2/denue_inegi_46321-46531_.csv"
df2 = pd.read_csv(csv_path2, encoding='latin-1')  # Try 'latin-1' encoding

print(df2.head())

df2.head()

/tmp/ipykernel_10618/2514030244.py:3: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(csv_path2, encoding='latin-1')  # Try 'latin-1' encoding

        id                          clee               nom_estab  \
0  9287941  01001464121002241000000000U8                + VISION
1  8541319  01001464121002151000000000S9                + VISION
2  8514602  01001464121001921000000000S6         + VISION OPTICA
3  7043395  01010465311000081000000000U7  101 COPIAS Y PAPELERIA
4  6281814  01001463211011603001007374S8   1011 TIENDAS ELECZION

                     raz_social  codigo_act  \
0                 GVMV SA DE CV      464121
1                 GMVM SA DE CV      464121
2                 GVMV SA DE CV      464121
3                           NaN      465311
4  GRUPO ELECZION S DE RL DE CV      463211

                                          nombre_act          per_ocu  \
0                    Comercio al por menor de lentes   0 a 5 personas
1                    Comercio al por menor de lentes   0 a 5 personas
2                    Comercio al por menor de lentes   0 a 5 personas
3    Comercio al por menor de artículos de papelería   0 a 5 personas
4  Comercio al por menor de ropa, excepto de bebé...  6 a 10 personas

  tipo_vial                    nom_vial    tipo_v_e_1  ...  \
0     CALLE             MONTES HIMALAYA     BOULEVARD  ...
1   AVENIDA  CONVENCION DE 1914 ORIENTE       AVENIDA  ...
2   AVENIDA          AGUASCALIENTES SUR  PROLONGACION  ...
3     CALLE              MELCHOR OCAMPO         CALLE  ...
4     CALLE                   5 DE MAYO         CALLE  ...

                                           localidad  ageb manzana telefono  \
0                                     Aguascalientes  0229       2      NaN
1                                     Aguascalientes  1354      15      NaN
2                                     Aguascalientes  0869      42      NaN
3  Palo Alto                                     ...  0143       1      NaN
4                                     Aguascalientes  0638      13      NaN

                        correoelec               www tipoUniEco    latitud  \
0  ATENCIONALCLIENTE@MASVISION.MXQ  WWW.MASVISION.MX       Fijo  21.923118
1     MV12933@OPTICAS.MASVISION.MX               NaN       Fijo  21.890777
2                              NaN               NaN       Fijo  21.859418
3                              NaN               NaN       Fijo  21.920380
4     STORE1011@GRUPOVISION.COM.MX  WWW.ELECZION.COM       Fijo  21.881665

     longitud  fecha_alta
0 -102.293833     2020-11
1 -102.274040     2019-11
2 -102.298205     2019-11
3 -101.963972     2019-11
4 -102.296788     2014-12

[5 rows x 42 columns]

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,...,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta
0,9287941,01001464121002241000000000U8,+ VISION,GVMV SA DE CV,464121,Comercio al por menor de lentes,0 a 5 personas,CALLE,MONTES HIMALAYA,BOULEVARD,...,Aguascalientes,0229,2,NaN,ATENCIONALCLIENTE@MASVISION.MXQ,WWW.MASVISION.MX,Fijo,21.923118,-102.293833,2020-11
1,8541319,01001464121002151000000000S9,+ VISION,GMVM SA DE CV,464121,Comercio al por menor de lentes,0 a 5 personas,AVENIDA,CONVENCION DE 1914 ORIENTE,AVENIDA,...,Aguascalientes,1354,15,NaN,MV12933@OPTICAS.MASVISION.MX,NaN,Fijo,21.890777,-102.274040,2019-11
2,8514602,01001464121001921000000000S6,+ VISION OPTICA,GVMV SA DE CV,464121,Comercio al por menor de lentes,0 a 5 personas,AVENIDA,AGUASCALIENTES SUR,PROLONGACION,...,Aguascalientes,0869,42,NaN,NaN,NaN,Fijo,21.859418,-102.298205,2019-11
3,7043395,01010465311000081000000000U7,101 COPIAS Y PAPELERIA,NaN,465311,Comercio al por menor de artículos de papelería,0 a 5 personas,CALLE,MELCHOR OCAMPO,CALLE,...,Palo Alto ...,0143,1,NaN,NaN,NaN,Fijo,21.920380,-101.963972,2019-11
4,6281814,01001463211011603001007374S8,1011 TIENDAS ELECZION,GRUPO ELECZION S DE RL DE CV,463211,"Comercio al por menor de ropa, excepto de bebé...",6 a 10 personas,CALLE,5 DE MAYO,CALLE,...,Aguascalientes,0638,13,NaN,STORE1011@GRUPOVISION.COM.MX,WWW.ELECZION.COM,Fijo,21.881665,-102.296788,2014-12

In [5]:
# Select only the specified columns from the second dataframe
df2_selected = df2[selected_columns]

print(df2_selected.head())

                           clee               nom_estab  codigo_act  \
0  01001464121002241000000000U8                + VISION      464121
1  01001464121002151000000000S9                + VISION      464121
2  01001464121001921000000000S6         + VISION OPTICA      464121
3  01010465311000081000000000U7  101 COPIAS Y PAPELERIA      465311
4  01001463211011603001007374S8   1011 TIENDAS ELECZION      463211

           per_ocu  cve_ent  cve_mun  cve_loc  ageb       municipio  \
0   0 a 5 personas        1        1        1  0229  Aguascalientes
1   0 a 5 personas        1        1        1  1354  Aguascalientes
2   0 a 5 personas        1        1        1  0869  Aguascalientes
3   0 a 5 personas        1       10        1  0143        El Llano
4  6 a 10 personas        1        1        1  0638  Aguascalientes

          entidad                                          localidad
0  Aguascalientes                                     Aguascalientes
1  Aguascalientes                                     Aguascalientes
2  Aguascalientes                                     Aguascalientes
3  Aguascalientes  Palo Alto                                     ...
4  Aguascalientes                                     Aguascalientes

In [6]:
# Filter df2_selected for codigo_act that starts with 46411
df2_filtered = df2_selected[df2_selected['codigo_act'].astype(str).str.startswith('46411')]
# BEGIN: Eliminate rows where 'codigo_act' is '464113'
df2_filtered = df2_filtered[df2_filtered['codigo_act'] != 464113]
# END:
print(df2_filtered.head())
# BEGIN: Eliminate rows from df_selected where 'codigo_act' is in the specified list
codigo_act_to_remove = [623311, 623312, 623991, 623992, 624111, 624112, 624191, 624198, 624199, 624211, 624212, 624221, 624222, 624231, 624232, 624311, 624312]
df_selected = df_selected[~df_selected['codigo_act'].isin(codigo_act_to_remove)]
# END:
print(df_selected.head())

                             clee  \
17   01001433110000172000000000U8
279  01001464111004021000000000U3
450  01001464113000381000000000U1
726  01001464111003431000000000U5
733  01001464111003271000000000U5

                                             nom_estab  codigo_act  \
17   ABASTECEDORA MEDICA HOSPITALARIA DE AGUASCALIE...      464111
279                               BIOFARMACIA FAMILIAR      464111
450                       BOTICA OMEOPATICA HAHANEMANN      464111
726                                  CLUB DE NUTRICION      464111
733                       CLUB DE NUTRICION HERBA LIFE      464111

              per_ocu  cve_ent  cve_mun  cve_loc  ageb       municipio  \
17   11 a 30 personas        1        1        1  0784  Aguascalientes
279    0 a 5 personas        1        1        1  3882  Aguascalientes
450    0 a 5 personas        1        1        1  0375  Aguascalientes
726    0 a 5 personas        1        1        1  0784  Aguascalientes
733    0 a 5 personas        1        1        1  3045  Aguascalientes

            entidad       localidad
17   Aguascalientes  Aguascalientes
279  Aguascalientes  Aguascalientes
450  Aguascalientes  Aguascalientes
726  Aguascalientes  Aguascalientes
733  Aguascalientes  Aguascalientes
                           clee  \
5  01006621331000011000000000U1
6  01001621211010761000000000U4
7  01001621111003671000000000U6
8  01001621115000051100000000U5
9  01001621391001471000000000U1

                                           nom_estab  codigo_act  \
5                               ACESORIA PSICOLOGICA      621331
6                            AD ODONTOLOGIA AVANZADA      621211
7  ADMINISTRACION DEL EDIFICIO GRUPO MEDICO HUMAN...      621111
8  ADMINSTRACION CENTRO DE ESPECIALIDADES MEDICAS...      621115
9                         ADRIANA IMAGEN Y NUTRICION      621391

          per_ocu  cve_ent  cve_mun  cve_loc  ageb            municipio  \
5  0 a 5 personas        1        6        1  0259  Pabellón de Arteaga
6  0 a 5 personas        1        1        1  2259       Aguascalientes
7  0 a 5 personas        1        1        1  2386       Aguascalientes
8  0 a 5 personas        1        1        1  0892       Aguascalientes
9  0 a 5 personas        1        1        1  2390       Aguascalientes

          entidad                                          localidad
5  Aguascalientes  Pabellón de Arteaga                           ...
6  Aguascalientes                                     Aguascalientes
7  Aguascalientes                                     Aguascalientes
8  Aguascalientes                                     Aguascalientes
9  Aguascalientes                                     Aguascalientes

In [37]:
df_mode = df2_filtered.groupby(['per_ocu']).count().reset_index()
df_mode

,per_ocu,clee,nom_estab,codigo_act,cve_ent,cve_mun,cve_loc,ageb,municipio,entidad,localidad
0,0 a 5 personas,53905,53905,53905,53905,53905,53905,53905,53905,53905,53905
1,101 a 250 personas,28,28,28,28,28,28,28,28,28,28
2,11 a 30 personas,5786,5786,5786,5786,5786,5786,5786,5786,5786,5786
3,251 y más personas,11,11,11,11,11,11,11,11,11,11
4,31 a 50 personas,225,225,225,225,225,225,225,225,225,225
5,51 a 100 personas,94,94,94,94,94,94,94,94,94,94
6,6 a 10 personas,5056,5056,5056,5056,5056,5056,5056,5056,5056,5056

In [24]:
# Create a new dataframe with only the specified columns
df_new = df_combined[['cve_mun', 'cve_ent', 'municipio', 'entidad']]

df_new = df_new.drop_duplicates()

df_new.to_csv('mapeo_clave_nombre.csv', index=False)

In [7]:
# Concatenate df_selected and df2_filtered
df_combined = pd.concat([df_selected, df2_filtered], ignore_index=True)

print(df_combined.head())
# Export the combined dataframe to a CSV file
df_combined.to_csv('instituciones_medicas.csv', index=False)

                           clee  \
0  01006621331000011000000000U1
1  01001621211010761000000000U4
2  01001621111003671000000000U6
3  01001621115000051100000000U5
4  01001621391001471000000000U1

                                           nom_estab  codigo_act  \
0                               ACESORIA PSICOLOGICA      621331
1                            AD ODONTOLOGIA AVANZADA      621211
2  ADMINISTRACION DEL EDIFICIO GRUPO MEDICO HUMAN...      621111
3  ADMINSTRACION CENTRO DE ESPECIALIDADES MEDICAS...      621115
4                         ADRIANA IMAGEN Y NUTRICION      621391

          per_ocu  cve_ent  cve_mun  cve_loc  ageb            municipio  \
0  0 a 5 personas        1        6        1  0259  Pabellón de Arteaga
1  0 a 5 personas        1        1        1  2259       Aguascalientes
2  0 a 5 personas        1        1        1  2386       Aguascalientes
3  0 a 5 personas        1        1        1  0892       Aguascalientes
4  0 a 5 personas        1        1        1  2390       Aguascalientes

          entidad                                          localidad
0  Aguascalientes  Pabellón de Arteaga                           ...
1  Aguascalientes                                     Aguascalientes
2  Aguascalientes                                     Aguascalientes
3  Aguascalientes                                     Aguascalientes
4  Aguascalientes                                     Aguascalientes

In [41]:
# Agrupar por municipio, entidad y localidad, y calcular el promedio de registros
df_grouped = df_selected.groupby(['municipio', 'entidad']).size().reset_index(name='número_registros')

# Mostrar el dataframe agrupado
print(df_grouped)
df_grouped.to_csv('registros_municipales_instituciones.csv', index=False)

            municipio                          entidad  número_registros
0               Abalá                          Yucatán                 2
1             Abasolo             Coahuila de Zaragoza                 4
2             Abasolo                       Guanajuato               100
3             Abasolo                       Nuevo León                 2
4             Abasolo                       Tamaulipas                 9
...               ...                              ...               ...
2446         Zumpango                           México               267
2447  Álamo Temapache  Veracruz de Ignacio de la Llave                88
2448   Álvaro Obregón                 Ciudad de México              1179
2449   Álvaro Obregón              Michoacán de Ocampo                36
2450   Ánimas Trujano                           Oaxaca                10

[2451 rows x 3 columns]

In [40]:
# Agrupar df2_filtered por municipio, entidad y localidad, y calcular el promedio de registros
df2_grouped = df2_filtered.groupby(['municipio', 'entidad']).size().reset_index(name='numero_registros')

# Mostrar el dataframe agrupado
print(df2_grouped)
df2_grouped.to_csv('registros_municipales_farmacias.csv', index=False)

            municipio                          entidad  numero_registros
0             Abasolo                       Guanajuato                28
1             Abasolo                       Tamaulipas                 6
2            Abejones                           Oaxaca                 1
3          Acacoyagua                          Chiapas                16
4             Acajete                           Puebla                34
...               ...                              ...               ...
2096         Zumpango                           México               161
2097  Álamo Temapache  Veracruz de Ignacio de la Llave                39
2098   Álvaro Obregón                 Ciudad de México               413
2099   Álvaro Obregón              Michoacán de Ocampo                14
2100   Ánimas Trujano                           Oaxaca                 1

[2101 rows x 3 columns]