### TAM analysis

In [1]:
import pandas as pd
from unidecode import unidecode

/home/luise/miniconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
path = '../bases_depuradas/ingreso_granular.csv' 
df = pd.read_csv(path, sep=',')
df.head()

,ï»¿folioviv,foliohog,ubica_geo,tam_loc,est_socio,est_dis,sexo_jefe,edad_jefe,educa_jefe,tot_integ,...,desc_mun,educa_jefe_desc,proporcion_mayores,sexo_jefe_desc_Mujer,est_socio_desc_Bajo,est_socio_desc_Medio alto,est_socio_desc_Medio bajo,tam_loc_desc_Localidades con 15 000 a 99 999 habitantes,tam_loc_desc_Localidades con 2 500 a 14 999 habitantes,tam_loc_desc_Localidades con menos de 2500 habitantes
0,100005002,1,1001,1,4,3,2,91,3,3,...,Aguascalientes,Primaria incompleta,0.333333,True,False,False,False,False,False,False
1,100005003,1,1001,1,4,3,1,68,8,2,...,Aguascalientes,Preparatoria completa,0.500000,False,False,False,False,False,False,False
2,100005004,1,1001,1,4,3,1,56,10,3,...,Aguascalientes,Profesional completa,0.000000,False,False,False,False,False,False,False
3,100012002,1,1001,1,3,2,1,87,11,4,...,Aguascalientes,Posgrado,0.500000,False,False,True,False,False,False,False
4,100012002,2,1001,1,3,2,1,27,8,1,...,Aguascalientes,Preparatoria completa,0.000000,False,False,True,False,False,False,False

In [3]:
# Group by 'desc_ent' and 'desc_mun' and calculate the mean for the specified columns
grouped_df = df.groupby(['desc_ent', 'desc_mun'])[['cuidados', 'salud', 'atenc_ambu', 'hospital', 'medicinas']].mean()
print(grouped_df)

                                         cuidados        salud   atenc_ambu  \
desc_ent       desc_mun
Aguascalientes Aguascalientes         2081.864819  1724.367999  1263.846898
               Asientos               1494.720368  1650.666074  1375.609264
               Calvillo               1586.915235  1730.225588  1447.547118
               Cosio                  1568.127222  1284.121667  1086.679444
               El Llano               2343.694554  3629.101881  3047.979802
...                                           ...          ...          ...
Zacatecas      Villa Garcia            933.293043   280.203043   189.056522
               Villa Gonzalez Ortega  1371.068182  1330.380758  1244.458788
               Villa Hidalgo          1006.638182   182.183091   159.916182
               Villanueva             1619.675278  1560.695833  1250.293056
               Zacatecas              2039.395385  1886.918097  1596.131781

                                        hospital   medicinas
desc_ent       desc_mun
Aguascalientes Aguascalientes         220.551289  239.969812
               Asientos                78.650613  196.406196
               Calvillo                10.358000  272.320471
               Cosio                    0.000000  197.442222
               El Llano               394.403168  186.718911
...                                          ...         ...
Zacatecas      Villa Garcia            44.659130   46.487391
               Villa Gonzalez Ortega    8.448485   77.473485
               Villa Hidalgo            1.067091   21.199818
               Villanueva               0.000000  310.402778
               Zacatecas               96.954534  193.831781

[1132 rows x 5 columns]

In [4]:
# Load the censo_depurado.csv file into a DataFrame
path_censo = '../bases_depuradas/censo_depurado.csv'
df_censo = pd.read_csv(path_censo, sep=',')
df_censo.head()

,Clave_Unica,ENTIDAD,MUNICIPIO,SECCION,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,Viviendas_Particulares_Con_Caracteristicas,Viviendas_Con_Drenaje
0,10010001,1,1,1,2564,36,650,2118,86,1385,756,753
1,10010002,1,1,2,889,27,213,713,26,479,277,275
2,10010003,1,1,3,2003,56,356,1579,64,1102,647,646
3,10010004,1,1,4,1636,40,267,1335,44,925,536,535
4,10010005,1,1,5,808,14,194,685,65,422,273,273

In [5]:
# Group by 'ENTIDAD' and 'MUNICIPIO' and calculate the sum for the specified columns
grouped_sum_df = df_censo.groupby(['ENTIDAD', 'MUNICIPIO']).sum()
grouped_sum_df = grouped_sum_df.drop('Clave_Unica', axis=1)
grouped_sum_df = grouped_sum_df.drop('SECCION', axis=1)
grouped_sum_df

                   Poblacion_Total  Poblacion_0_a_2_anios  \
ENTIDAD MUNICIPIO
1       1                   942696                  44175
        2                    51601                   3174
        3                    58340                   3162
        4                    16984                   1032
        5                   134795                   7055
...                            ...                    ...
32      54                   19459                   1251
        55                   31623                   1409
        56                  148829                   6492
        57                   20455                   1308
        58                    2765                    123

                   Poblacion_Mayores_60  Poblacion_Afiliada_Salud  \
ENTIDAD MUNICIPIO
1       1                        102411                    769637
        2                          4703                     43985
        3                          7832                     46413
        4                          1613                     14639
        5                         10296                    106024
...                                 ...                       ...
32      54                         2128                     16444
        55                         5648                     23647
        56                        18639                    123278
        57                         1785                     17549
        58                          530                      2350

                   Poblacion_Discapacidad  Poblacion_Economicamente_Activa  \
ENTIDAD MUNICIPIO
1       1                           47389                           483478
        2                            2892                            21470
        3                            4091                            26038
        4                             804                             7002
        5                            5084                            68291
...                                   ...                              ...
32      54                           1401                             6685
        55                           2135                            13721
        56                           8415                            72143
        57                           1020                             8312
        58                            174                              922

                   Viviendas_Particulares_Con_Caracteristicas  \
ENTIDAD MUNICIPIO
1       1                                              264444
        2                                               12537
        3                                               15539
        4                                                3926
        5                                               34900
...                                                       ...
32      54                                               4952
        55                                               9049
        56                                              42077
        57                                               4668
        58                                                857

                   Viviendas_Con_Drenaje
ENTIDAD MUNICIPIO
1       1                         263328
        2                          12078
        3                          15427
        4                           3880
        5                          34595
...                                  ...
32      54                          4651
        55                          8676
        56                         41821
        57                          4455
        58                           818

[2468 rows x 8 columns]

In [6]:
df_instituciones = pd.read_csv('datos/registros_municipales_instituciones.csv')
df_farmacias = pd.read_csv('datos/registros_municipales_farmacias.csv')
df_instituciones
df_farmacias

            municipio                          entidad  numero_registros
0             Abasolo                       Guanajuato                28
1             Abasolo                       Tamaulipas                 6
2            Abejones                           Oaxaca                 1
3          Acacoyagua                          Chiapas                16
4             Acajete                           Puebla                34
...               ...                              ...               ...
2096         Zumpango                           México               161
2097  Álamo Temapache  Veracruz de Ignacio de la Llave                39
2098   Álvaro Obregón                 Ciudad de México               413
2099   Álvaro Obregón              Michoacán de Ocampo                14
2100   Ánimas Trujano                           Oaxaca                 1

[2101 rows x 3 columns]

In [7]:
df_farmacias['entidad'] = df_farmacias['entidad'].apply(unidecode)
df_farmacias['municipio'] = df_farmacias['municipio'].apply(unidecode)
df_farmacias['entidad'] = df_farmacias['entidad'].str.replace(' ', '').str.upper()
df_farmacias['municipio'] = df_farmacias['municipio'].str.replace(' ', '').str.upper()
df_instituciones['entidad'] = df_instituciones['entidad'].apply(unidecode)
df_instituciones['municipio'] = df_instituciones['municipio'].apply(unidecode)
df_instituciones['entidad'] = df_instituciones['entidad'].str.replace(' ', '').str.upper()
df_instituciones['municipio'] = df_instituciones['municipio'].str.replace(' ', '').str.upper()

In [8]:
df_farmacias.rename(columns={'numero_registros': 'numero_de_farmacias'}, inplace=True)
df_instituciones.rename(columns={'número_registros': 'numero_de_instituciones'}, inplace=True)

In [9]:
df_mapeo = pd.read_csv("datos/mapeo_clave_nombre.csv")
df_mapeo

      cve_mun  cve_ent            municipio                          entidad
0           6        1  Pabellón de Arteaga                   Aguascalientes
1           1        1       Aguascalientes                   Aguascalientes
2           7        1      Rincón de Romos                   Aguascalientes
3           5        1          Jesús María                   Aguascalientes
4           3        1             Calvillo                   Aguascalientes
...       ...      ...                  ...                              ...
2455      448       20   Santa María Zaniza                           Oaxaca
2456       61       21         Eloxochitlán                           Puebla
2457       78       21  Huitzilan de Serdán                           Puebla
2458       19       30            Astacinga  Veracruz de Ignacio de la Llave
2459       68       31             Sinanché                          Yucatán

[2460 rows x 4 columns]

In [10]:
df_tam = df_mapeo.copy()
df_demo = grouped_sum_df.copy()
df_granular = grouped_df.copy()

In [11]:
df_demo_reset = df_demo.reset_index()
df_demo_reset.head()

,ENTIDAD,MUNICIPIO,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,Viviendas_Particulares_Con_Caracteristicas,Viviendas_Con_Drenaje
0,1,1,942696,44175,102411,769637,47389,483478,264444,263328
1,1,2,51601,3174,4703,43985,2892,21470,12537,12078
2,1,3,58340,3162,7832,46413,4091,26038,15539,15427
3,1,4,16984,1032,1613,14639,804,7002,3926,3880
4,1,5,134795,7055,10296,106024,5084,68291,34900,34595

In [12]:
df_granular = df_granular.reset_index()
df_granular.head()

,desc_ent,desc_mun,cuidados,salud,atenc_ambu,hospital,medicinas
0,Aguascalientes,Aguascalientes,2081.864819,1724.367999,1263.846898,220.551289,239.969812
1,Aguascalientes,Asientos,1494.720368,1650.666074,1375.609264,78.650613,196.406196
2,Aguascalientes,Calvillo,1586.915235,1730.225588,1447.547118,10.358000,272.320471
3,Aguascalientes,Cosio,1568.127222,1284.121667,1086.679444,0.000000,197.442222
4,Aguascalientes,El Llano,2343.694554,3629.101881,3047.979802,394.403168,186.718911

In [13]:
df_tam['entidad'] = df_tam['entidad'].apply(unidecode)
df_tam['municipio'] = df_tam['municipio'].apply(unidecode)
df_tam['entidad'] = df_tam['entidad'].str.replace(' ', '').str.upper()
df_tam['municipio'] = df_tam['municipio'].str.replace(' ', '').str.upper()
df_granular['desc_ent'] = df_granular['desc_ent'].str.replace(' ', '').str.upper()
df_granular['desc_mun'] = df_granular['desc_mun'].str.replace(' ', '').str.upper()

In [14]:
df_tam_merged = df_tam.merge(df_demo_reset, left_on=['cve_mun', 'cve_ent'], right_on=['MUNICIPIO', 'ENTIDAD'], how='left')
df_tam = df_tam_merged.drop(['ENTIDAD', 'MUNICIPIO'], axis=1)
df_tam

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,Viviendas_Particulares_Con_Caracteristicas,Viviendas_Con_Drenaje
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,11218.0,11106.0
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,264444.0,263328.0
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,13549.0,13308.0
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,34900.0,34595.0
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,15539.0,15427.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,4429.0,4147.0
2456,61,21,ELOXOCHITLAN,PUEBLA,7784.0,531.0,714.0,4098.0,271.0,3642.0,1795.0,1674.0
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,7738.0,7243.0
2458,19,30,ASTACINGA,VERACRUZDEIGNACIODELALLAVE,1978.0,128.0,188.0,1523.0,133.0,669.0,485.0,409.0
2459,68,31,SINANCHE,YUCATAN,3201.0,132.0,613.0,2812.0,325.0,1284.0,984.0,890.0

In [15]:
df_tam_merged = df_tam.merge(df_granular, left_on=['municipio', 'entidad'], right_on=['desc_mun', 'desc_ent'], how='left')
df_tam = df_tam_merged.drop(['desc_mun', 'desc_ent'], axis=1)
df_tam

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,Viviendas_Particulares_Con_Caracteristicas,Viviendas_Con_Drenaje,cuidados,salud,atenc_ambu,hospital,medicinas
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,11218.0,11106.0,1862.996565,964.259389,709.129695,85.056183,170.073511
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,264444.0,263328.0,2081.864819,1724.367999,1263.846898,220.551289,239.969812
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,13549.0,13308.0,2123.971818,1767.281909,927.333091,592.523273,247.425545
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,34900.0,34595.0,2333.125019,2174.889119,1062.373870,813.001801,299.513448
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,15539.0,15427.0,1586.915235,1730.225588,1447.547118,10.358000,272.320471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,4429.0,4147.0,887.460833,132.913333,55.026250,0.000000,77.887083
2456,61,21,ELOXOCHITLAN,PUEBLA,7784.0,531.0,714.0,4098.0,271.0,3642.0,1795.0,1674.0,NaN,NaN,NaN,NaN,NaN
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,7738.0,7243.0,NaN,NaN,NaN,NaN,NaN
2458,19,30,ASTACINGA,VERACRUZDEIGNACIODELALLAVE,1978.0,128.0,188.0,1523.0,133.0,669.0,485.0,409.0,NaN,NaN,NaN,NaN,NaN
2459,68,31,SINANCHE,YUCATAN,3201.0,132.0,613.0,2812.0,325.0,1284.0,984.0,890.0,NaN,NaN,NaN,NaN,NaN

In [16]:
df_tam = df_tam.merge(df_farmacias, left_on=['municipio', 'entidad'], right_on=['municipio', 'entidad'], how='left')
df_tam

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,Viviendas_Particulares_Con_Caracteristicas,Viviendas_Con_Drenaje,cuidados,salud,atenc_ambu,hospital,medicinas,numero_de_farmacias
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,11218.0,11106.0,1862.996565,964.259389,709.129695,85.056183,170.073511,17.0
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,264444.0,263328.0,2081.864819,1724.367999,1263.846898,220.551289,239.969812,352.0
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,13549.0,13308.0,2123.971818,1767.281909,927.333091,592.523273,247.425545,15.0
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,34900.0,34595.0,2333.125019,2174.889119,1062.373870,813.001801,299.513448,30.0
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,15539.0,15427.0,1586.915235,1730.225588,1447.547118,10.358000,272.320471,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,4429.0,4147.0,887.460833,132.913333,55.026250,0.000000,77.887083,1.0
2456,61,21,ELOXOCHITLAN,PUEBLA,7784.0,531.0,714.0,4098.0,271.0,3642.0,1795.0,1674.0,NaN,NaN,NaN,NaN,NaN,1.0
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,7738.0,7243.0,NaN,NaN,NaN,NaN,NaN,4.0
2458,19,30,ASTACINGA,VERACRUZDEIGNACIODELALLAVE,1978.0,128.0,188.0,1523.0,133.0,669.0,485.0,409.0,NaN,NaN,NaN,NaN,NaN,3.0
2459,68,31,SINANCHE,YUCATAN,3201.0,132.0,613.0,2812.0,325.0,1284.0,984.0,890.0,NaN,NaN,NaN,NaN,NaN,1.0

In [17]:
df_tam = df_tam.merge(df_instituciones, left_on=['municipio', 'entidad'], right_on=['municipio', 'entidad'], how='left')
df_tam

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,Viviendas_Particulares_Con_Caracteristicas,Viviendas_Con_Drenaje,cuidados,salud,atenc_ambu,hospital,medicinas,numero_de_farmacias,numero_de_instituciones
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,11218.0,11106.0,1862.996565,964.259389,709.129695,85.056183,170.073511,17.0,73.0
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,264444.0,263328.0,2081.864819,1724.367999,1263.846898,220.551289,239.969812,352.0,2505.0
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,13549.0,13308.0,2123.971818,1767.281909,927.333091,592.523273,247.425545,15.0,67.0
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,34900.0,34595.0,2333.125019,2174.889119,1062.373870,813.001801,299.513448,30.0,120.0
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,15539.0,15427.0,1586.915235,1730.225588,1447.547118,10.358000,272.320471,16.0,95.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,4429.0,4147.0,887.460833,132.913333,55.026250,0.000000,77.887083,1.0,NaN
2456,61,21,ELOXOCHITLAN,PUEBLA,7784.0,531.0,714.0,4098.0,271.0,3642.0,1795.0,1674.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,7738.0,7243.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2458,19,30,ASTACINGA,VERACRUZDEIGNACIODELALLAVE,1978.0,128.0,188.0,1523.0,133.0,669.0,485.0,409.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
2459,68,31,SINANCHE,YUCATAN,3201.0,132.0,613.0,2812.0,325.0,1284.0,984.0,890.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN

In [18]:
df_tam['TAM'] = df_tam['Poblacion_Total'] * df_tam['medicinas']
df_tam

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,Viviendas_Particulares_Con_Caracteristicas,Viviendas_Con_Drenaje,cuidados,salud,atenc_ambu,hospital,medicinas,numero_de_farmacias,numero_de_instituciones,TAM
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,11218.0,11106.0,1862.996565,964.259389,709.129695,85.056183,170.073511,17.0,73.0,7.938011e+06
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,264444.0,263328.0,2081.864819,1724.367999,1263.846898,220.551289,239.969812,352.0,2505.0,2.262186e+08
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,13549.0,13308.0,2123.971818,1767.281909,927.333091,592.523273,247.425545,15.0,67.0,1.419183e+07
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,34900.0,34595.0,2333.125019,2174.889119,1062.373870,813.001801,299.513448,30.0,120.0,4.037292e+07
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,15539.0,15427.0,1586.915235,1730.225588,1447.547118,10.358000,272.320471,16.0,95.0,1.588718e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,4429.0,4147.0,887.460833,132.913333,55.026250,0.000000,77.887083,1.0,NaN,1.336075e+06
2456,61,21,ELOXOCHITLAN,PUEBLA,7784.0,531.0,714.0,4098.0,271.0,3642.0,1795.0,1674.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,7738.0,7243.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
2458,19,30,ASTACINGA,VERACRUZDEIGNACIODELALLAVE,1978.0,128.0,188.0,1523.0,133.0,669.0,485.0,409.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
2459,68,31,SINANCHE,YUCATAN,3201.0,132.0,613.0,2812.0,325.0,1284.0,984.0,890.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN

In [19]:
## min min_habitantes
rh = 0.06/1000
df_tam['phalc'] = df_tam['Poblacion_Total'] * rh
fph = 4.9
df_tam['Farm_alc'] = df_tam['phalc']/fph
df_tam['Pers_Farm'] = df_tam['Poblacion_Total'] / df_tam['Farm_alc']

In [20]:
df_tam

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,...,salud,atenc_ambu,hospital,medicinas,numero_de_farmacias,numero_de_instituciones,TAM,phalc,Farm_alc,Pers_Farm
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,...,964.259389,709.129695,85.056183,170.073511,17.0,73.0,7.938011e+06,2.80044,0.571518,81666.666667
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,...,1724.367999,1263.846898,220.551289,239.969812,352.0,2505.0,2.262186e+08,56.56176,11.543216,81666.666667
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,...,1767.281909,927.333091,592.523273,247.425545,15.0,67.0,1.419183e+07,3.44148,0.702343,81666.666667
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,...,2174.889119,1062.373870,813.001801,299.513448,30.0,120.0,4.037292e+07,8.08770,1.650551,81666.666667
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,...,1730.225588,1447.547118,10.358000,272.320471,16.0,95.0,1.588718e+07,3.50040,0.714367,81666.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,...,132.913333,55.026250,0.000000,77.887083,1.0,NaN,1.336075e+06,1.02924,0.210049,81666.666667
2456,61,21,ELOXOCHITLAN,PUEBLA,7784.0,531.0,714.0,4098.0,271.0,3642.0,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.46704,0.095314,81666.666667
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,1.69272,0.345453,81666.666667
2458,19,30,ASTACINGA,VERACRUZDEIGNACIODELALLAVE,1978.0,128.0,188.0,1523.0,133.0,669.0,...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,0.11868,0.024220,81666.666667
2459,68,31,SINANCHE,YUCATAN,3201.0,132.0,613.0,2812.0,325.0,1284.0,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.19206,0.039196,81666.666667

In [21]:
## mayor gasto en tipos de salud .75
## precencia de instituciones de salud .25

df_tam_filtered = df_tam[df_tam['Poblacion_Total'] >= 10000]

gasto_promedio = df_tam_filtered['salud'].mean()
instituciones_promedio = df_tam_filtered['numero_de_instituciones'].mean()

df_tam_filtered['SAM'] = df_tam_filtered['TAM'] * (
    (0.75 * df_tam_filtered['salud']/gasto_promedio + 0.25 * df_tam_filtered['numero_de_instituciones']/instituciones_promedio) / 100
)

df_tam_filtered['SAM']

/tmp/ipykernel_287598/2002515929.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tam_filtered['SAM'] = df_tam_filtered['TAM'] * (

0       5.686514e+04
1       1.333368e+07
2       1.679147e+05
3       6.173074e+05
4       1.931081e+05
            ...
2447    2.292011e+03
2448    1.903541e+03
2453             NaN
2455             NaN
2457             NaN
Name: SAM, Length: 1432, dtype: float64

In [22]:
df_tam_filtered

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,...,atenc_ambu,hospital,medicinas,numero_de_farmacias,numero_de_instituciones,TAM,phalc,Farm_alc,Pers_Farm,SAM
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,...,709.129695,85.056183,170.073511,17.0,73.0,7.938011e+06,2.80044,0.571518,81666.666667,5.686514e+04
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,...,1263.846898,220.551289,239.969812,352.0,2505.0,2.262186e+08,56.56176,11.543216,81666.666667,1.333368e+07
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,...,927.333091,592.523273,247.425545,15.0,67.0,1.419183e+07,3.44148,0.702343,81666.666667,1.679147e+05
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,...,1062.373870,813.001801,299.513448,30.0,120.0,4.037292e+07,8.08770,1.650551,81666.666667,6.173074e+05
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,...,1447.547118,10.358000,272.320471,16.0,95.0,1.588718e+07,3.50040,0.714367,81666.666667,1.931081e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,7,32,CONCEPCIONDELORO,ZACATECAS,12216.0,572.0,1917.0,10361.0,818.0,5008.0,...,218.800417,271.059167,52.661667,5.0,17.0,6.433149e+05,0.73296,0.149584,81666.666667,2.292011e+03
2448,52,32,VILLAGARCIA,ZACATECAS,19527.0,1119.0,2130.0,15280.0,1032.0,8037.0,...,189.056522,44.659130,46.487391,10.0,22.0,9.077593e+05,1.17162,0.239106,81666.666667,1.903541e+03
2453,40,13,LAMISION,HIDALGO,202795.0,6970.0,17483.0,142823.0,8962.0,109256.0,...,835.578500,0.000000,34.627000,1.0,NaN,7.022182e+06,12.16770,2.483204,81666.666667,NaN
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,...,55.026250,0.000000,77.887083,1.0,NaN,1.336075e+06,1.02924,0.210049,81666.666667,NaN
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,...,NaN,NaN,NaN,4.0,NaN,NaN,1.69272,0.345453,81666.666667,NaN

In [23]:
df_tam_filtered['SOM'] = df_tam_filtered['SAM'] / (df_tam_filtered['numero_de_farmacias']+1)
df_tam_filtered

/tmp/ipykernel_287598/3330121832.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tam_filtered['SOM'] = df_tam_filtered['SAM'] / (df_tam_filtered['numero_de_farmacias']+1)

,cve_mun,cve_ent,municipio,entidad,Poblacion_Total,Poblacion_0_a_2_anios,Poblacion_Mayores_60,Poblacion_Afiliada_Salud,Poblacion_Discapacidad,Poblacion_Economicamente_Activa,...,hospital,medicinas,numero_de_farmacias,numero_de_instituciones,TAM,phalc,Farm_alc,Pers_Farm,SAM,SOM
0,6,1,PABELLONDEARTEAGA,AGUASCALIENTES,46674.0,2680.0,4401.0,37929.0,2571.0,21681.0,...,85.056183,170.073511,17.0,73.0,7.938011e+06,2.80044,0.571518,81666.666667,5.686514e+04,3159.174248
1,1,1,AGUASCALIENTES,AGUASCALIENTES,942696.0,44175.0,102411.0,769637.0,47389.0,483478.0,...,220.551289,239.969812,352.0,2505.0,2.262186e+08,56.56176,11.543216,81666.666667,1.333368e+07,37772.459971
2,7,1,RINCONDEROMOS,AGUASCALIENTES,57358.0,3546.0,5264.0,45797.0,3324.0,26676.0,...,592.523273,247.425545,15.0,67.0,1.419183e+07,3.44148,0.702343,81666.666667,1.679147e+05,10494.666998
3,5,1,JESUSMARIA,AGUASCALIENTES,134795.0,7055.0,10296.0,106024.0,5084.0,68291.0,...,813.001801,299.513448,30.0,120.0,4.037292e+07,8.08770,1.650551,81666.666667,6.173074e+05,19913.140966
4,3,1,CALVILLO,AGUASCALIENTES,58340.0,3162.0,7832.0,46413.0,4091.0,26038.0,...,10.358000,272.320471,16.0,95.0,1.588718e+07,3.50040,0.714367,81666.666667,1.931081e+05,11359.302937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,7,32,CONCEPCIONDELORO,ZACATECAS,12216.0,572.0,1917.0,10361.0,818.0,5008.0,...,271.059167,52.661667,5.0,17.0,6.433149e+05,0.73296,0.149584,81666.666667,2.292011e+03,382.001873
2448,52,32,VILLAGARCIA,ZACATECAS,19527.0,1119.0,2130.0,15280.0,1032.0,8037.0,...,44.659130,46.487391,10.0,22.0,9.077593e+05,1.17162,0.239106,81666.666667,1.903541e+03,173.049219
2453,40,13,LAMISION,HIDALGO,202795.0,6970.0,17483.0,142823.0,8962.0,109256.0,...,0.000000,34.627000,1.0,NaN,7.022182e+06,12.16770,2.483204,81666.666667,NaN,NaN
2455,448,20,SANTAMARIAZANIZA,OAXACA,17154.0,1009.0,2212.0,12536.0,1780.0,7639.0,...,0.000000,77.887083,1.0,NaN,1.336075e+06,1.02924,0.210049,81666.666667,NaN,NaN
2457,78,21,HUITZILANDESERDAN,PUEBLA,28212.0,1511.0,3579.0,20905.0,1272.0,14219.0,...,NaN,NaN,4.0,NaN,NaN,1.69272,0.345453,81666.666667,NaN,NaN

In [24]:
# Select the relevant columns and sort by 'SOM'
df_ordered = df_tam_filtered[['municipio', 'entidad', 'Poblacion_Total', 'numero_de_farmacias', 'numero_de_instituciones', 'SOM']].sort_values(by='SOM', ascending=False)

# Display the ordered DataFrame
df_ordered.head(15)

,municipio,entidad,Poblacion_Total,numero_de_farmacias,numero_de_instituciones,SOM
191,TAPALAPA,CHIAPAS,352419.0,3.0,4.0,1.007836e+06
549,TEQUILA,JALISCO,150163.0,21.0,94.0,4.035978e+05
9,ELLLANO,AGUASCALIENTES,64147.0,2.0,9.0,8.702962e+04
213,ASCENSION,CHIHUAHUA,26157.0,14.0,33.0,8.237292e+04
295,TOPIA,DURANGO,21430.0,2.0,4.0,6.803574e+04
437,TLAPEHUALA,GUERRERO,95554.0,12.0,34.0,5.591687e+04
628,TECHALUTADEMONTENEGRO,JALISCO,16587.0,3.0,3.0,4.963719e+04
30,CALKINI,CAMPECHE,294635.0,18.0,65.0,4.754709e+04
1811,LAZAROCARDENAS,QUINTANAROO,233648.0,10.0,17.0,4.130062e+04
1,AGUASCALIENTES,AGUASCALIENTES,942696.0,352.0,2505.0,3.777246e+04
1995,MIGUELALEMAN,TAMAULIPAS,26219.0,13.0,120.0,3.680583e+04
399,AYUTLADELOSLIBRES,GUERRERO,67771.0,30.0,55.0,3.623119e+04
374,CHILPANCINGODELOSBRAVO,GUERRERO,283342.0,84.0,539.0,3.530820e+04
207,JUAREZ,CHIHUAHUA,1512451.0,502.0,2029.0,3.402061e+04
114,TUXTLACHICO,CHIAPAS,604089.0,12.0,26.0,3.151808e+04